"use client";

import { Shield, FileText, Lock, Scale } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

export function Compliance() {
    const stats = [
        { title: "Fail-Closed", subtitle: "Defaults to Denial", icon: <Shield size={40} className="text-silver-bright mb-2" /> },
        { title: "Audit Trails", subtitle: "JSON-L Decision Logs", icon: <FileText size={40} className="text-silver-bright mb-2" /> },
        { title: "Sovereign", subtitle: "Your Keys, Your Infra", icon: <Lock size={40} className="text-silver-bright mb-2" /> },
        { title: "Attestable", subtitle: "Signed Audit Trails", icon: <Scale size={40} className="text-silver-bright mb-2" /> },
    ];

    return (
        <section id="compliance" className="py-24 bg-navy-light/10 border-t border-white/5">
            <div className="container px-6 text-center">
                <h2 className="text-3xl font-bold text-silver-bright mb-4">Designed for Engineering Rigor</h2>
                <p className="text-silver-dim text-lg mb-16 max-w-2xl mx-auto">
                    Technical architecture to support your audit workflows. Not a certification.
                </p>

                <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                    {stats.map((stat, i) => (
                        <div key={i} className="p-8 rounded-xl bg-white/2 border border-white/5 hover:border-gold/30 hover:bg-gold/5 transition-all">
                            <div className="flex justify-center">{stat.icon}</div>
                            <h4 className="text-xl font-bold text-white mt-4">{stat.title}</h4>
                            <p className="text-silver-dim text-sm mt-1">{stat.subtitle}</p>
                        </div>
                    ))}
                </div>

                <p className="mt-12 text-sm text-silver-dim/60 italic max-w-2xl mx-auto">
                    *ATLAS provides technical controls, not legal compliance. Operators remain fully responsible for regulatory verification, legal review, and all code generated by the system.
                </p>
            </div>
        </section>
    );
}
