import { Footer } from "@/components/Footer";

export default function TermsPage() {
    return (
        <main className="flex flex-col min-h-screen pt-24">
            <div className="container px-6 py-12 max-w-4xl mx-auto">
                <h1 className="text-4xl font-bold text-white mb-8">Terms of Use</h1>

                <div className="prose prose-invert max-w-none text-silver-dim">
                    <p className="mb-6">
                        Last Updated: January 14, 2026
                    </p>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
                        <p>
                            By accessing or using ATLAS NOMOS ("the System"), you agree to be bound by these Terms of Use.
                            The System is experimental governance software provided for sovereign AI execution verification.
                            If you do not agree to these terms, do not use the System.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-white mb-4">2. Nature of Service</h2>
                        <p>
                            ATLAS is provided "AS-IS" as a technical framework for liability containment and audit trail generation.
                            It does not constitute legal advice, insurance, or a guarantee of safety. You acknowledge that you are
                            software operator utilizing the System at your own risk.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-white mb-4">3. Operator Responsibility</h2>
                        <p>
                            You maintain full legal and ethical responsibility for all output generated by AI models governed by this System.
                            ATLAS provides tools for oversight, but does not absolve the operator of liability for downstream harms.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-white mb-4">4. Intellectual Property</h2>
                        <p>
                            The core framework of ATLAS is open-source under the MIT License. However, specific proprietary modules
                            and the "ATLAS NOMOS" trademark are reserved.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-white mb-4">5. Modifications</h2>
                        <p>
                            We reserve the right to modify these terms at any time. Continued use of the System following changes
                            constitutes acceptance of those changes.
                        </p>
                    </section>
                </div>
            </div>
            <Footer />
        </main>
    );
}
